### ISSUE TITLE
Typo in arxiv version paper

### ISSUE THREAD

**Issue by Gutianpei** [viewsetting/Unsupervised_sampling_promoting#1]
In page 2 Related Work section.

![image](https://user-images.githubusercontent.com/21379120/235255911-6b0e728d-00e0-4666-935e-bcb39ea2b54f.png)

**Comment by viewsetting** [comment]
Thank you for pointing out our typo. We will fix it in the later version.

**Comment by Gutianpei** [comment]
I'll close the issue then. Congrats on the great work!
