### ISSUE TITLE
pretrained model for PECNet

### ISSUE THREAD

**Issue by thisishale** [viewsetting/Unsupervised_sampling_promoting#2]
Hi, Thank you for providing the code for your paper.
I tried your code with the PECNet model I trained myself, and I am getting size mismatch errors when loading the model. 
Would it be possible for you to provide your pre-trained models for PECNet?
Thanks.

**Comment by viewsetting** [comment]
Sorry, I have uploaded the pre-trained weights. The commit is: https://github.com/viewsetting/Unsupervised_sampling_promoting/commit/5f7001c3b9e73d8a092d60cfa4964b92cccc0ea5 . If you have further issues to report, feel free to open new issues. Thanks.
